---
title: "Analisi bibliometrica della letteratura scientifica prodotta dai ricercatori IZSLER"
author: "Gruppo Project Ricerca"
date: "16 settembre 2019"
output: 
  ioslides_presentation: 
    smaller: yes
    widescreen: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(bibliometrix)
library(Matrix)
library(stringr)
library(igraph)
library(FactoMineR)
library(factoextra)
library(scholar)
library(topicmodels)
library(tidytext)
library(tm)
library(ggthemes)

izsler<- readFiles("wos1izsler.bib","wos2izsler.bib","wos3izsler.bib")
izsler <- convert2df(izsler, dbsource = "wos", format = "bibtex")

```

## Fonte dati

Web of Science Core Collection (Clarivate Analytics)
(http://http://www.webofknowledge.com/)

Strategia di ricerca

campo di ricerca: Organization-Enhanced

stringa di ricerca: IZS Lombardia e Emilia

Periodo 1981-2019 (analizzato periodo 2005-2019)



## Produzione 
<div style="margin-left:-50px; margin-top:-50px; width:900px">
```{r prod}
inputPanel(
 sliderInput("anno", "Periodo:",
                  min = 1981, max = 2019,
                  value = c("2005","2019"))
)



renderPlot({
  
  izsler %>% 
  filter(PY>=input$anno[1] & PY<input$anno[2]) %>% 
  group_by(PY) %>% 
  summarise(n=n()) %>% 
  ggplot(aes(x=PY, y=n))+geom_point(stat = "identity")+
  geom_line(stat="identity")+
  labs(x="Anno di pubblicazione", y="Numero articoli pubblicati")+
  scale_x_continuous(breaks=c(1981:2018))
  
  
  
})
```

## Sorgenti
<div style="margin-left:-50px; margin-top:-50px; width:900px">
```{r sorg}
inputPanel(
 sliderInput("anno2", "Periodo:",
                  min = 1981, max = 2019,
                  value = c("2005","2019"))
)

renderPlot({
  
  izsler %>% 
  filter(PY>=input$anno2[1] & PY<input$anno2[2]) %>% 
  group_by(SO) %>% 
  summarise(n=n()) %>% 
  top_n(10, n) %>% 
  arrange(n) %>% 
  mutate(SO = factor(SO, unique(SO))) %>%
  ggplot(aes(x=SO, y=n))+geom_bar(stat = "identity", fill="red")+coord_flip()
})
```






## R Output

```{r cars}
summary(cars)
```


