---
title: "Indagine sull'integrazione tecnico-scientifiche al supporto amministrativo alle ricerche"
author: "Gruppo Project Ricerca"
date: "xx settembre 2019"
output: 
  ioslides_presentation: 
    smaller: yes
    widescreen: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
library(tidyverse)
library(bibliometrix)
library(Matrix)
library(stringr)
library(igraph)
library(FactoMineR)
library(factoextra)
library(scholar)
library(topicmodels)
library(tidytext)
library(tm)
library(ggthemes)
library(DataExplorer)
library(googlesheets)
library(plyr)
dati<-gs_title("Integrazione tecnico-scientifica alle attività amministrative a supporto della ricerca (Risposte)")
ds <-gs_read(dati, ws="Risposte del modulo 1" )

library(plyr)
ds$Professione<-revalue(ds$Professione, c("Collaboratore tecnico professionale addetto ai servizi di laboratorio"="Tecnico di laboratorio", "Tecnico sanitario di laboratorio biomedico"="Tecnico di laboratorio"))
                         

ds$`Ruolo esclusivo o prevalente in Istituto`<-revalue(
  ds$`Ruolo esclusivo o prevalente in Istituto`, c(
    "Tecnico" ="Tecnico di laboratorio" , 
    "Collaboratore tecnico professionale addetto ai servizi di laboratorio"=
      "Tecnico di laboratorio" , "professional e gestionale" ="Gestionale e tecnico/scientifico" , "gestionale e professional"  ="Gestionale e tecnico/scientifico" , "gestionale con mantenimento di attività tecnico-scientifica"="Gestionale e tecnico/scientifico" ))
  




```

### Risultati
```{r risultati}
ds %>% 
      group_by(Professione) %>% 
      summarise(n=n()) %>% 
      arrange(n) %>% 
      mutate(Professione = factor(Professione, unique(Professione))) %>%
      ggplot(aes(x=Professione, y=n))+ geom_bar(stat="identity", fill="steelblue3")+labs(x="")+
      coord_flip()+theme(axis.text=element_text(size=12))



```




## Produttività
<div style="margin-left:-50px; margin-top:-50px; width:900px">
```{r prod}
inputPanel(
 sliderInput("anno", "Periodo:",
                  min = 1981, max = 2019,
                  value = c("2005","2019"))
)



renderPlot({
  
  izsler %>% 
  filter(PY>=input$anno[1] & PY<input$anno[2]) %>% 
  group_by(PY) %>% 
  summarise(n=n()) %>% 
  ggplot(aes(x=PY, y=n))+geom_point(stat = "identity")+
  geom_line(stat="identity")+
  labs(x="Anno di pubblicazione", y="Numero articoli pubblicati")+
  scale_x_continuous(breaks=c(1981:2018))
  
  
  
})
```

## Sorgenti
<div style="margin-left:-50px; margin-top:-50px; width:900px">
```{r sorg}
inputPanel(
 sliderInput("anno2", "Periodo:",
                  min = 1981, max = 2019,
                  value = c("2005","2019"))
)

renderPlot({
  
  izsler %>% 
  filter(PY>=input$anno2[1] & PY<input$anno2[2]) %>% 
  group_by(SO) %>% 
  summarise(n=n()) %>% 
  top_n(10, n) %>% 
  arrange(n) %>% 
  mutate(SO = factor(SO, unique(SO))) %>%
  ggplot(aes(x=SO, y=n))+geom_bar(stat = "identity", fill="red")+coord_flip()
})
```






## R Output

```{r cars}
summary(cars)
```


