---
title: "Survey"
author: "Max"
date: "27 settembre 2019"
output: html_document
runtime: shiny
---

---
title: "Indagine esigenze tecnico-scientifiche in supporto all'attività di ricerca"
author: "Gruppo Project Ricerca"
date: "xx settembre 2019"
output: 
  ioslides_presentation: 
    smaller: yes
    widescreen: yes
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
library(tidyverse)
library(bibliometrix)
library(Matrix)
library(stringr)
library(igraph)
library(FactoMineR)
library(factoextra)
library(scholar)
library(topicmodels)
library(tidytext)
library(tm)
library(ggthemes)
library(googlesheets)
library(plyr)
library(kableExtra)
library(knitr)


source("score.R")


dati<-gs_title("Integrazione tecnico-scientifica alle attività amministrative a supporto della ricerca (Risposte)")
ds <-gs_read(dati, ws="Risposte del modulo 1" )
ds<-ds[-1,]

names(ds)[c(5,6,7,8)]<-c("Estero", "Ruolo", "Risposta", "Servizio")

ds<- ds %>% drop_na(Risposta)
ds<-ds %>% 
  mutate(id=seq(1:dim(ds)[1]))
ds$Professione<-revalue(ds$Professione, c("Collaboratore tecnico professionale addetto ai servizi di laboratorio"="Tecnico di laboratorio", "Tecnico sanitario di laboratorio biomedico"="Tecnico di laboratorio"))
                         
ds$Ruolo<-revalue(
  ds$Ruolo, c(
    "Tecnico" ="Tecnico di laboratorio" , 
    "Collaboratore tecnico professionale addetto ai servizi di laboratorio"=
      "Tecnico di laboratorio" , "professional e gestionale" ="Gestionale e tecnico/scientifico" , "gestionale e professional"  ="Gestionale e tecnico/scientifico" , "gestionale con mantenimento di attività tecnico-scientifica"="Gestionale e tecnico/scientifico" ))

ds$wordCount <- sapply(gregexpr("\\W+", ds$Risposta), length) 


f<-ds %>% 
  group_by(Formazione) %>% 
 
  dplyr::summarise(Risposte=n(), "Età media"=mean(`Età`, na.rm=TRUE)," Servizio"=median(Servizio, na.rm=TRUE)) %>% 
mutate_if(is.numeric, funs(round(.,digits = 2))) %>% 
arrange(desc(Risposte))
  
kable(f,format='markdown')


p<-ds %>% 
  group_by(Professione) %>% 
 
  dplyr::summarise(Risposte=n(), "Età media"=mean(`Età`, na.rm=TRUE)," Servizio"=median(Servizio, na.rm=TRUE), 
                   "minS"=min(Servizio, na.rm=TRUE), "maxS"=max(Servizio, na.rm=TRUE)) %>% 
mutate_if(is.numeric, funs(round(.,digits = 2))) %>% 
arrange(desc(Risposte))
  
kable(p,format='markdown')



r<-ds %>% 
  group_by(Ruolo) %>% 
 
  dplyr::summarise(Risposte=n(), "Età media"=mean(`Età`, na.rm=TRUE)," Servizio"=median(Servizio, na.rm=TRUE), 
                   "minS"=min(Servizio, na.rm=TRUE), "maxS"=max(Servizio, na.rm=TRUE)) %>% 
mutate_if(is.numeric, funs(round(.,digits = 2))) %>% 
arrange(desc(Risposte))
  
kable(r,format='markdown')



```

### Risultati

```{r for, echo=FALSE}

f<-ds %>% 
  group_by(Formazione) %>% 
 
  dplyr::summarise(Risposte=n(), "Età media"=mean(`Età`, na.rm=TRUE),"Anni di Servizio"=median(Servizio, na.rm=TRUE)) %>% 
mutate_if(is.numeric, funs(round(.,digits = 2))) %>% 
arrange(desc(Risposte))
  
kable(f,format='markdown')





  
```