library(tidyverse)
library(bibliometrix)
library(Matrix)
library(stringr)
library(igraph)
library(FactoMineR)
library(factoextra)
library(scholar)
library(topicmodels)
library(tidytext)
library(tm)
library(ggthemes)
library(DT)
library(knitr)
library(kableExtra)

izsler<- readFiles("wos1izsler.bib","wos2izsler.bib","wos3izsler.bib")
izsler <- convert2df(izsler, dbsource = "wos", format = "bibtex")
izsve<- readFiles("izve1.bib","izve2.bib","izve3.bib")
izsve <- convert2df(izsve, dbsource = "wos", format = "bibtex")

results <-biblioAnalysis(izsler, sep = ";")
S<-summary(results, k = 10, pause = FALSE)
kable(S$MainInformationDF) %>% 
  kable_styling(bootstrap_options = c("striped",full_width = F, position = "float_right"))
